// Fallback articles shown when live RSS feeds are unavailable.
// URLs link to verified section/topic pages — never guessed article paths.
module.exports = [
  {
    id: 'seed-001',
    title: 'OpenAI Launches GPT-5 with Reasoning Upgrades Targeting Enterprise Workflows',
    summary: 'OpenAI\'s latest model delivers significant improvements in multi-step reasoning, code generation, and structured output — capabilities that enterprise SaaS vendors are racing to embed into their platforms.',
    url: 'https://openai.com/blog/',
    image: null,
    publishedAt: new Date().toISOString(),
    source: 'OpenAI Blog',
    category: 'general',
    tags: ['ai', 'models', 'enterprise'],
  },
  {
    id: 'seed-002',
    title: 'The Agentic Era: How AI Agents Are Reshaping B2B Software Purchasing',
    summary: 'As AI agents gain the ability to autonomously evaluate, trial, and purchase software, the traditional B2B SaaS sales motion faces its most significant disruption in a decade.',
    url: 'https://a16z.com/topic/artificial-intelligence/',
    image: null,
    publishedAt: new Date(Date.now() - 3600000).toISOString(),
    source: 'a16z',
    category: 'saas',
    tags: ['saas', 'agents', 'venture'],
  },
  {
    id: 'seed-003',
    title: 'Anthropic Releases Claude 3.5 Sonnet: Enterprise Safety Benchmarks Set New Bar',
    summary: 'New safety evals show Claude 3.5 outperforming competitors on jailbreak resistance and harmful-output avoidance — a key differentiator for regulated-industry SaaS deployments.',
    url: 'https://www.anthropic.com/news',
    image: null,
    publishedAt: new Date(Date.now() - 7200000).toISOString(),
    source: 'Anthropic',
    category: 'general',
    tags: ['ai', 'safety', 'enterprise'],
  },
  {
    id: 'seed-004',
    title: 'Salesforce Agentforce Reaches 1 Million Active Deployments',
    summary: 'Salesforce\'s AI agent platform has crossed a major milestone, with deployments spanning sales automation, customer service, and revenue intelligence across Fortune 500 firms.',
    url: 'https://www.salesforce.com/news/',
    image: null,
    publishedAt: new Date(Date.now() - 10800000).toISOString(),
    source: 'Salesforce News',
    category: 'saas',
    tags: ['crm', 'enterprise', 'agents'],
  },
  {
    id: 'seed-005',
    title: 'Why AI Won\'t Replace SaaS — It Will Unbundle It',
    summary: 'The prevailing fear that AI will kill SaaS misses the bigger story: AI is disaggregating monolithic suites into modular capabilities, creating new winners and losers in every vertical.',
    url: 'https://stratechery.com/',
    image: null,
    publishedAt: new Date(Date.now() - 14400000).toISOString(),
    source: 'Stratechery',
    category: 'thought-leadership',
    tags: ['analysis', 'saas', 'strategy'],
  },
  {
    id: 'seed-006',
    title: 'Google DeepMind Gemini 2.0 Shows Strong Multimodal Enterprise Reasoning',
    summary: 'DeepMind\'s latest Gemini model outperforms on long-context document analysis and complex multi-step tasks, with Google positioning the capability directly at enterprise productivity.',
    url: 'https://deepmind.google/technologies/gemini/',
    image: null,
    publishedAt: new Date(Date.now() - 18000000).toISOString(),
    source: 'Google DeepMind',
    category: 'general',
    tags: ['ai', 'research', 'models'],
  },
  {
    id: 'seed-007',
    title: 'The $100B AI Infrastructure Build-Out: What SaaS Founders Need to Know',
    summary: 'Hyperscaler capex on AI infrastructure has surpassed $100B annually. For SaaS founders, this means lower inference costs, new platform primitives, and a race to capture AI-native distribution.',
    url: 'https://a16z.com/topic/infrastructure/',
    image: null,
    publishedAt: new Date(Date.now() - 21600000).toISOString(),
    source: 'a16z',
    category: 'saas',
    tags: ['infrastructure', 'saas', 'venture'],
  },
  {
    id: 'seed-008',
    title: 'Microsoft Copilot Saves Enterprise Users 4.4 Hours Per Week on Routine Tasks',
    summary: 'Microsoft\'s internal study shows Copilot users saving an average of 4.4 hours per week — but adoption stalls without proper change management and workflow integration.',
    url: 'https://www.microsoft.com/en-us/worklab/',
    image: null,
    publishedAt: new Date(Date.now() - 25200000).toISOString(),
    source: 'Microsoft Blog',
    category: 'saas',
    tags: ['enterprise', 'copilot', 'productivity'],
  },
  {
    id: 'seed-009',
    title: 'Open Source LLMs Close the Gap on GPT-4 for Vertical SaaS Use Cases',
    summary: 'Fine-tuned open-source models like Llama 3.3 and Mistral Large are achieving near-parity with frontier models on domain-specific tasks — at a fraction of the inference cost.',
    url: 'https://huggingface.co/blog',
    image: null,
    publishedAt: new Date(Date.now() - 28800000).toISOString(),
    source: 'Hugging Face Blog',
    category: 'general',
    tags: ['ai', 'open-source', 'models'],
  },
  {
    id: 'seed-010',
    title: 'How CIOs Are Evaluating AI-Native vs. AI-Augmented SaaS Vendors',
    summary: 'Enterprise CIOs are drawing a sharp line between vendors bolting AI onto legacy stacks and those rebuilding core workflows from the ground up. The purchasing criteria have fundamentally shifted.',
    url: 'https://venturebeat.com/ai/',
    image: null,
    publishedAt: new Date(Date.now() - 32400000).toISOString(),
    source: 'VentureBeat AI',
    category: 'saas',
    tags: ['enterprise', 'strategy', 'procurement'],
  },
  {
    id: 'seed-011',
    title: 'The Real Costs of Running AI in Production: A SaaS Founder\'s Guide',
    summary: 'Token costs, latency budgets, eval pipelines, observability — the pragmatic engineering work of running AI features in production is harder and more expensive than the demos suggest.',
    url: 'https://newsletter.pragmaticengineer.com/',
    image: null,
    publishedAt: new Date(Date.now() - 36000000).toISOString(),
    source: 'The Pragmatic Engineer',
    category: 'saas',
    tags: ['engineering', 'mlops', 'saas'],
  },
  {
    id: 'seed-012',
    title: 'Sequoia\'s AI Velocity Report: Vertical AI Is Monetizing 3x Faster',
    summary: 'Sequoia\'s latest analysis of AI startup revenue trajectories reveals that vertical AI for legal, medical, and financial services is monetizing 3x faster than horizontal productivity tools.',
    url: 'https://www.sequoiacap.com/our-views/ai/',
    image: null,
    publishedAt: new Date(Date.now() - 39600000).toISOString(),
    source: 'Sequoia Capital',
    category: 'saas',
    tags: ['venture', 'market-data', 'vertical-ai'],
  },
  {
    id: 'seed-013',
    title: 'What the EU AI Act Means for B2B Software Companies Selling in Europe',
    summary: 'The EU AI Act\'s tiered risk framework will require significant compliance work from B2B SaaS vendors selling into European markets. Here\'s what changes in 2025 and beyond.',
    url: 'https://www.technologyreview.com/topic/artificial-intelligence/',
    image: null,
    publishedAt: new Date(Date.now() - 43200000).toISOString(),
    source: 'MIT Technology Review',
    category: 'general',
    tags: ['regulation', 'compliance', 'enterprise'],
  },
  {
    id: 'seed-014',
    title: 'AWS Bedrock Usage Doubles Quarter-Over-Quarter Among Enterprise Customers',
    summary: 'Amazon Web Services reports accelerating enterprise adoption of Bedrock, its managed AI foundation model service, with financial services and healthcare leading sector growth.',
    url: 'https://aws.amazon.com/blogs/machine-learning/',
    image: null,
    publishedAt: new Date(Date.now() - 46800000).toISOString(),
    source: 'AWS Machine Learning',
    category: 'saas',
    tags: ['cloud', 'enterprise', 'infrastructure'],
  },
  {
    id: 'seed-015',
    title: 'Benedict Evans on the AI Platform Shift: Winners, Losers, and Timing',
    summary: 'Evans argues that AI is less a product category and more a platform shift comparable to mobile — predicting winners requires understanding which incumbents will transition vs. which get disrupted.',
    url: 'https://www.ben-evans.com/',
    image: null,
    publishedAt: new Date(Date.now() - 50400000).toISOString(),
    source: 'Benedict Evans',
    category: 'thought-leadership',
    tags: ['analysis', 'strategy', 'platform'],
  },
  {
    id: 'seed-016',
    title: 'The AI Researchers Trying to Make Language Models Honest',
    summary: 'A new generation of alignment researchers is focused on the more immediate problem of making AI systems reliably truthful in business contexts — not just preventing catastrophic risk.',
    url: 'https://www.wired.com/tag/artificial-intelligence/',
    image: null,
    publishedAt: new Date(Date.now() - 54000000).toISOString(),
    source: 'Wired AI',
    category: 'general',
    tags: ['research', 'safety', 'alignment'],
  },
];
